# Generated by Django 5.2.7 on 2025-10-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergen",
            name="common",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
        migrations.AlterField(
            model_name="allergen",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
