# Generated by Django 5.2.7 on 2025-10-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_allergen_common_tag_verified_user_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="certificate",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
