# Generated by Django 5.2.7 on 2025-10-19 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tag_certificate'),
        ('meal_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_users', to='meal_planner.mealplan'),
        ),
    ]
