# Generated by Django 5.2.7 on 2025-10-21 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_user_tags(apps, schema_editor):
    """Migrate existing user-tag relationships to UserTag model"""
    User = apps.get_model("accounts", "User")
    UserTag = apps.get_model("accounts", "UserTag")

    # For each user, create UserTag entries for their existing tags
    for user in User.objects.all():
        for tag in user.tags.all():
            UserTag.objects.get_or_create(
                user=user, tag=tag, defaults={"verified": False, "certificate": None}
            )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_current_meal_plan"),
    ]

    operations = [
        # Step 1: Remove certificate and verified from Tag model
        migrations.RemoveField(
            model_name="tag",
            name="certificate",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="verified",
        ),
        # Step 2: Create UserTag model
        migrations.CreateModel(
            name="UserTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "certificate",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tag")},
            },
        ),
        # Step 3: Migrate existing data to UserTag
        migrations.RunPython(migrate_user_tags, reverse_code=migrations.RunPython.noop),
        # Step 4: Remove old tags field
        migrations.RemoveField(
            model_name="user",
            name="tags",
        ),
        # Step 5: Add new tags field with through='UserTag'
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(
                blank=True, through="accounts.UserTag", to="accounts.tag"
            ),
        ),
    ]
