# Generated by Django 5.2.8 on 2025-11-09 21:34

import accounts.models
import uuid
from django.db import migrations, models


def generate_unique_tokens(apps, schema_editor):
    """Generate unique UUIDs for existing User and UserTag records"""
    import os
    from django.conf import settings

    User = apps.get_model("accounts", "User")
    UserTag = apps.get_model("accounts", "UserTag")

    # Generate tokens for existing users
    for user in User.objects.all():
        user.profile_image_token = uuid.uuid4()
        user.save()

        # If user has a profile image, rename the file to use the new token
        if user.profile_image:
            old_path = os.path.join(settings.MEDIA_ROOT, user.profile_image.name)
            if os.path.exists(old_path):
                ext = os.path.splitext(user.profile_image.name)[1]
                new_name = f"profile_images/{user.profile_image_token}{ext}"
                new_path = os.path.join(settings.MEDIA_ROOT, new_name)

                # Rename the file on disk
                os.makedirs(os.path.dirname(new_path), exist_ok=True)
                if old_path != new_path:  # Only rename if different
                    os.rename(old_path, new_path)
                    user.profile_image = new_name
                    user.save()

    # Generate tokens for existing user tags
    for user_tag in UserTag.objects.all():
        user_tag.certificate_token = uuid.uuid4()
        user_tag.save()

        # If user_tag has a certificate, rename the file to use the new token
        if user_tag.certificate:
            old_path = os.path.join(settings.MEDIA_ROOT, user_tag.certificate.name)
            if os.path.exists(old_path):
                ext = os.path.splitext(user_tag.certificate.name)[1]
                new_name = f"certificates/{user_tag.certificate_token}{ext}"
                new_path = os.path.join(settings.MEDIA_ROOT, new_name)

                # Rename the file on disk
                os.makedirs(os.path.dirname(new_path), exist_ok=True)
                if old_path != new_path:  # Only rename if different
                    os.rename(old_path, new_path)
                    user_tag.certificate = new_name
                    user_tag.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0006_remove_tag_certificate_remove_tag_verified_usertag_and_more",
        ),
    ]

    operations = [
        # Step 1: Add fields without unique constraint
        migrations.AddField(
            model_name="user",
            name="profile_image_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="usertag",
            name="certificate_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        # Step 2: Populate unique values and rename files
        migrations.RunPython(generate_unique_tokens, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name="user",
            name="profile_image_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="usertag",
            name="certificate_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        # Step 4: Update file fields to use new upload_to
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.profile_image_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="usertag",
            name="certificate",
            field=models.FileField(
                blank=True, null=True, upload_to=accounts.models.certificate_upload_to
            ),
        ),
    ]
