# Generated by Django 5.2.8 on 2025-11-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_report"),
        (
            "accounts",
            "0007_user_profile_image_token_usertag_certificate_token_and_more",
        ),
    ]

    operations = []
