# Generated by Django 5.2.7 on 2025-11-20 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionTargets',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutrition_targets', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('calories', models.DecimalField(decimal_places=2, help_text='Daily calorie target', max_digits=7)),
                ('protein', models.DecimalField(decimal_places=2, help_text='Daily protein target in grams', max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=2, help_text='Daily carbohydrates target in grams', max_digits=6)),
                ('fat', models.DecimalField(decimal_places=2, help_text='Daily fat target in grams', max_digits=6)),
                ('micronutrients', models.JSONField(blank=True, default=dict, help_text='Daily micronutrient targets (e.g., vitamins, minerals)')),
                ('is_custom', models.BooleanField(default=False, help_text='True if manually set, False if auto-calculated from metrics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Nutrition Targets',
            },
        ),
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metrics', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in centimeters', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5)),
                ('age', models.PositiveIntegerField(help_text='Age in years')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Light (exercise 1-3 days/week)'), ('moderate', 'Moderate (exercise 3-5 days/week)'), ('active', 'Active (exercise 6-7 days/week)'), ('very_active', 'Very Active (hard exercise & physical job)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User Metrics',
            },
        ),
    ]
