# Generated by Django 5.2 on 2025-05-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="foodentry",
            name="allergens",
        ),
        migrations.AddField(
            model_name="foodentry",
            name="allergens",
            field=models.ManyToManyField(
                blank=True, related_name="food_entries", to="foods.allergen"
            ),
        ),
    ]
