# Generated by Django 5.2.1 on 2025-05-11 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_allergen_remove_foodentry_allergens_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("servingSize", models.FloatField()),
                ("caloriesPerServing", models.FloatField()),
                ("proteinContent", models.FloatField()),
                ("fatContent", models.FloatField()),
                ("carbohydrateContent", models.FloatField()),
                ("dietaryOptions", models.JSONField(default=list)),
                ("nutritionScore", models.FloatField()),
                ("imageUrl", models.URLField(blank=True)),
                ("isApproved", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "allergens",
                    models.ManyToManyField(
                        blank=True, related_name="food_proposals", to="foods.allergen"
                    ),
                ),
                (
                    "proposedBy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
