# Generated by Django 5.2 on 2025-05-11 16:58

from django.db import migrations
import json
import os
import sys
import django


def load_data(apps, schema_editor):
    """
    For loading food data manualy into the database, but we need to run this script in the Django context.
    """
    json_path = os.path.join(
        os.path.dirname(__file__), "../../api/db_initialization/foods.json"
    )
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    try:
        FoodEntry = apps.get_model("foods", "FoodEntry")
        for item in data:
            """Create a FoodEntry object for each item in the JSON file and save it to the database."""
            FoodEntry.objects.create(
                name=item["name"],
                category=item["category"],
                servingSize=item["servingSize"],
                caloriesPerServing=item["caloriesPerServing"],
                proteinContent=item["proteinContent"],
                fatContent=item["fatContent"],
                carbohydrateContent=item["carbohydrateContent"],
                dietaryOptions=item.get("dietaryOptions", []),
                nutritionScore=item["nutritionScore"],
                imageUrl=item.get("imageUrl"),
            )
    except Exception as e:
        print(f"An error occurred: {e}")
    finally:
        print("Food data loading completed.")


def backwards(apps, schema_editor):
    FoodEntry = apps.get_model("foods", "FoodEntry")
    FoodEntry.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0003_foodproposal"),
    ]

    operations = [
        migrations.RunPython(load_data, backwards),
    ]
