# Generated by Django 5.2.8 on 2025-11-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0005_update_food_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("original_url", models.TextField()),
                ("cached_file", models.ImageField(upload_to="cached_images/")),
                (
                    "content_type",
                    models.CharField(default="image/jpeg", max_length=100),
                ),
                ("file_size", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("access_count", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["last_accessed"], name="foods_image_last_ac_759784_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="foods_image_created_60afe1_idx"
                    ),
                ],
            },
        ),
    ]
