# Generated by Django 5.2.8 on 2025-11-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0006_imagecache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodproposal",
            name="isApproved",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
