# Generated by Django 5.2.7 on 2025-11-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_alter_foodproposal_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='micronutrients',
            field=models.JSONField(blank=True, default=dict, help_text='Micronutrient content (vitamins, minerals) per serving'),
        ),
        migrations.AddField(
            model_name='foodproposal',
            name='micronutrients',
            field=models.JSONField(blank=True, default=dict, help_text='Micronutrient content (vitamins, minerals) per serving'),
        ),
    ]
