# Generated by Django 5.2.1 on 2025-05-10 20:07

from django.db import migrations


def create_default_tags(apps, schema_editor):
    Tag = apps.get_model("forum", "Tag")
    default_tags = ["Dietary tip", "Recipe", "Meal plan"]
    for name in default_tags:
        Tag.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_tag_post_tags"),
    ]

    operations = [
        migrations.RunPython(create_default_tags),
    ]
