# Generated by Django 5.2.1 on 2025-05-10 19:16

from django.db import migrations


def create_dietary_tags(apps, schema_editor):
    Tag = apps.get_model('forum', 'Tag')
    
    # Create dietary tags
    dietary_tags = [
        'Vegan',
        'Halal',
        'High-Protein'
    ]
    
    for tag_name in dietary_tags:
        Tag.objects.get_or_create(name=tag_name)


def remove_dietary_tags(apps, schema_editor):
    Tag = apps.get_model('forum', 'Tag')
    
    # Remove dietary tags
    dietary_tags = [
        'Vegan',
        'Halal',
        'High-Protein'
    ]
    
    Tag.objects.filter(name__in=dietary_tags).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0006_recipe_recipeingredient"),
    ]

    operations = [
        migrations.RunPython(create_dietary_tags, remove_dietary_tags),
    ]

