# Generated by Django 5.2.7 on 2025-11-20 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_foodentry_micronutrients_foodproposal_micronutrients'),
        ('meal_planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of this nutrition log')),
                ('total_calories', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_fat', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_carbohydrates', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('micronutrients_summary', models.JSONField(blank=True, default=dict, help_text='Aggregated micronutrient totals for the day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FoodLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.DecimalField(decimal_places=2, help_text='Serving size multiplier (e.g., 2 for two servings)', max_digits=6)),
                ('serving_unit', models.CharField(default='serving', help_text='Unit of measurement (e.g., serving, cup, gram)', max_length=50)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=7)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=7)),
                ('micronutrients', models.JSONField(blank=True, default=dict, help_text='Micronutrient values for this serving')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='meal_planner.dailynutritionlog')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to='foods.foodentry')),
            ],
            options={
                'verbose_name_plural': 'Food Log Entries',
                'ordering': ['logged_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dailynutritionlog',
            index=models.Index(fields=['user', 'date'], name='meal_planne_user_id_22ad5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailynutritionlog',
            unique_together={('user', 'date')},
        ),
    ]
